### ISSUE TITLE
Using commands

### ISSUE THREAD

**Issue by frizib** [Zwuiix-cmd/EasyProxy#3]
Which mask should I use to execute commands?
/ or // or . or ! ?

**Comment by Zwuiix-cmd** [comment]
You have to use // to execute a command, for example //proxy, //stop, //about, //version !

**Comment by frizib** [comment]
In general, nothing is output to the chat after entering these commands.

**Comment by Zwuiix-cmd** [comment]
An option to hide commands will appear soon

**Comment by frizib** [comment]
Cool of course, but my //version, //about etc don't work

**Comment by Zwuiix-cmd** [comment]
hmmm... Are you well connected with the proxy?

**Comment by frizib** [comment]
Sure. When logging in, he even writes that I logged in with a proxy

**Comment by Zwuiix-cmd** [comment]
This is very strange, would you have discord?

**Comment by frizib** [comment]
yes

**Comment by Zwuiix-cmd** [comment]
Add Diango#0001

**Comment by Zwuiix-cmd** [comment]
and send your username (i have 300 friend request)

**Comment by frizib** [comment]
![image](https://user-images.githubusercontent.com/28644006/216800214-de8c2335-bc18-4d7f-9100-6cd9aa909a2c.png)

**Comment by Zwuiix-cmd** [comment]
check last commit

**Comment by Zwuiix-cmd** [comment]
Fix!
